[package]
name = "rust-examples"
version = "0.1.0"
edition = "2021"
build = "src/build.rs"

[build-dependencies]
capnpc = "0.21.0"

[dependencies]
base64 = "0.22.1"
capnp = "0.21.0"
chrono = "0.4.41"
